# .travis.yml

# Do not set the language to c++, this over rides our environment variable CXX
# below.
language: C++

sudo: false

git:
    depth: 1

addons:
  apt:
    sources:
       - ubuntu-toolchain-r-test
    packages:
       - g++-5

os:
  - linux

env:
  - CXX="ccache g++-5"

# OMR compiles with g++, so ccache works for it
cache:
  ccache: true
  directories:
    - node_modules

before_install:
  - pip install --user cpp-coveralls

install:
  - npm install

script:
  - mkdir build && cd build
  - cmake -DB9_GCOV ..
  - make -j8 || echo "RETRYING BUILD!" && make -j1 VERBOSE=1 # On failure, retry with verbose output
  - ctest --output-on-failure

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
