# .travis.yml

# Do not set the language to c++, this over rides our environment variable CXX
# below.
language: C++

sudo: false

git:
    depth: 1

addons:
  apt:
    sources:
       - ubuntu-toolchain-r-test
    packages:
       - g++-5

os:
  - linux

cache:
  ccache: true
  directories:
    - node_modules

install:
  - npm install
  - pip install --user cpp-coveralls

before_script:
  - export CXX="ccache g++-5"
  - export CC="ccache gcc-5"
  - export GCOV="gcov-5"

script:
  - mkdir build && cd build
  - cmake -DB9_GCOV=ON ..
  - make -j8 || echo "*BUILD_FAILURE*" && make -j1 VERBOSE=1 # On failure, retry with verbose output
  - ctest --output-on-failure
  - cd "${TRAVIS_BUILD_DIR}"

after_script:
  - cd "$TRAVIS_BUILD_DIR}"
  - coveralls --exclude third_party --gcov /usr/bin/gcov-5 --gcov-options '\-lp' --build-root build
